# IPEDS TABLE MERGE

## Filtering schools based on our requirements

In [ ]:
import pandas as pd

table1 = pd.read_csv("C2023_B_final.csv")
table2 = pd.read_csv("EF2023_final.csv")
table3 = pd.read_csv("IC2023_sorted.csv")

In [ ]:
# Merge the first two tables on 'UNITID'
merged_df = pd.merge(table1, table2, on='UNITID', how='inner')

# Merge the result with the third table
filter_df = pd.merge(merged_df, table3, on='UNITID', how='inner')

filter_df.head(10)

,UNITID,CSTOTLT,EFLEVEL,EFTOTAL,CNTLAFFI,LEVEL3,LEVEL4,LEVEL5,LEVEL6,LEVEL7,LEVEL8,LEVEL17,LEVEL18,LEVEL19,STUSRV8
0,100654,729,10,6614,1,0,0,1,0,1,1,1,0,0,1
1,100663,6356,10,21160,1,0,0,1,1,1,1,1,1,0,0
2,100690,171,10,636,4,1,0,1,0,1,0,1,0,0,0
3,100706,2288,10,8743,1,0,0,1,1,1,1,1,1,0,1
4,100724,598,10,3870,1,0,0,1,1,1,1,1,1,0,0
5,100751,8929,10,39622,1,0,1,1,1,1,1,1,1,0,1
6,100760,232,10,1910,1,1,0,-2,-2,-2,-2,-2,-2,-2,0
7,100812,837,10,2955,1,0,0,1,1,1,0,0,0,0,0
8,100830,1256,10,5189,1,0,0,1,1,1,1,1,1,0,1
9,100858,7764,10,33015,1,0,0,1,1,1,1,1,1,1,0

In [ ]:
filter_df.shape

(3406, 15)

In [ ]:
filter_df = filter_df[filter_df['CSTOTLT'] >= 50]
filter_df.shape

(3003, 15)

In [ ]:
filter_df = filter_df[filter_df['EFTOTAL'] >= 200]
filter_df.shape

(2919, 15)

In [ ]:
filter_df.head(10)

,UNITID,CSTOTLT,EFLEVEL,EFTOTAL,CNTLAFFI,LEVEL3,LEVEL4,LEVEL5,LEVEL6,LEVEL7,LEVEL8,LEVEL17,LEVEL18,LEVEL19,STUSRV8
0,100654,729,10,6614,1,0,0,1,0,1,1,1,0,0,1
1,100663,6356,10,21160,1,0,0,1,1,1,1,1,1,0,0
2,100690,171,10,636,4,1,0,1,0,1,0,1,0,0,0
3,100706,2288,10,8743,1,0,0,1,1,1,1,1,1,0,1
4,100724,598,10,3870,1,0,0,1,1,1,1,1,1,0,0
5,100751,8929,10,39622,1,0,1,1,1,1,1,1,1,0,1
6,100760,232,10,1910,1,1,0,-2,-2,-2,-2,-2,-2,-2,0
7,100812,837,10,2955,1,0,0,1,1,1,0,0,0,0,0
8,100830,1256,10,5189,1,0,0,1,1,1,1,1,1,0,1
9,100858,7764,10,33015,1,0,0,1,1,1,1,1,1,1,0

In [ ]:
filter_df.to_csv('filter_final.csv', index=False)

## Merge with HD2023

In [ ]:
hd2023 = pd.read_csv("HD2023.csv")
hd2023.head(10)

,UNITID,INSTNM,IALIAS,ADDR,CITY,STABBR,ZIP,FIPS,OBEREG,CHFNM,...,CBSA,CBSATYPE,CSA,COUNTYCD,COUNTYNM,CNGDSTCD,LONGITUD,LATITUDE,DFRCGID,DFRCUSCG
0,100654,Alabama A & M University,AAMU,4900 Meridian Street,Normal,AL,35762,1,5,Dr. Daniel K. Wims,...,26620,1,290,1089,Madison County,105,-86.568502,34.783368,106,1
1,100663,University of Alabama at Birmingham,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,1,5,Ray L. Watts,...,13820,1,142,1073,Jefferson County,107,-86.799345,33.505697,91,1
2,100690,Amridge University,Southern Christian University Regions University,1200 Taylor Rd,Montgomery,AL,36117-3553,1,5,Michael C.Turner,...,33860,1,388,1101,Montgomery County,102,-86.174010,32.362609,124,2
3,100706,University of Alabama in Huntsville,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,1,5,Chuck Karr,...,26620,1,290,1089,Madison County,105,-86.640449,34.724557,91,1
4,100724,Alabama State University,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,1,5,Quinton T. Ross,...,33860,1,388,1101,Montgomery County,107,-86.295677,32.364317,97,1
5,100733,University of Alabama System Office,NaN,500 University Blvd. East,Tuscaloosa,AL,35401,1,5,Finis St. John IV,...,46220,1,-2,1125,Tuscaloosa County,107,-87.529594,33.207015,-2,-2
6,100751,The University of Alabama,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,1,5,Dr. Stuart R. Bell,...,46220,1,-2,1125,Tuscaloosa County,107,-87.545978,33.211875,90,1
7,100760,Central Alabama Community College,NaN,1675 Cherokee Rd,Alexander City,AL,35010,1,5,Jeff Lynn,...,10760,2,194,1123,Tallapoosa County,103,-85.945266,32.924780,72,2
8,100812,Athens State University,NaN,300 N Beaty St,Athens,AL,35611,1,5,Dr. Catherine Wehlburg,...,26620,1,290,1083,Limestone County,105,-86.964698,34.806793,133,1
9,100830,Auburn University at Montgomery,AUM||Auburn University at Montgomery|Auburn Mo...,7440 East Drive,Montgomery,AL,36117-3596,1,5,Carl A. Stockton,...,33860,1,388,1101,Montgomery County,102,-86.177544,32.367360,106,1

In [ ]:
merged = pd.merge(filter_df, hd2023, on='UNITID', how='inner')
merged.head(10)

,UNITID,CSTOTLT,EFLEVEL,EFTOTAL,CNTLAFFI,LEVEL3,LEVEL4,LEVEL5,LEVEL6,LEVEL7,...,CBSA,CBSATYPE,CSA,COUNTYCD,COUNTYNM,CNGDSTCD,LONGITUD,LATITUDE,DFRCGID,DFRCUSCG
0,100654,729,10,6614,1,0,0,1,0,1,...,26620,1,290,1089,Madison County,105,-86.568502,34.783368,106,1
1,100663,6356,10,21160,1,0,0,1,1,1,...,13820,1,142,1073,Jefferson County,107,-86.799345,33.505697,91,1
2,100690,171,10,636,4,1,0,1,0,1,...,33860,1,388,1101,Montgomery County,102,-86.174010,32.362609,124,2
3,100706,2288,10,8743,1,0,0,1,1,1,...,26620,1,290,1089,Madison County,105,-86.640449,34.724557,91,1
4,100724,598,10,3870,1,0,0,1,1,1,...,33860,1,388,1101,Montgomery County,107,-86.295677,32.364317,97,1
5,100751,8929,10,39622,1,0,1,1,1,1,...,46220,1,-2,1125,Tuscaloosa County,107,-87.545978,33.211875,90,1
6,100760,232,10,1910,1,1,0,-2,-2,-2,...,10760,2,194,1123,Tallapoosa County,103,-85.945266,32.924780,72,2
7,100812,837,10,2955,1,0,0,1,1,1,...,26620,1,290,1083,Limestone County,105,-86.964698,34.806793,133,1
8,100830,1256,10,5189,1,0,0,1,1,1,...,33860,1,388,1101,Montgomery County,102,-86.177544,32.367360,106,1
9,100858,7764,10,33015,1,0,0,1,1,1,...,12220,1,194,1081,Lee County,103,-85.488258,32.599378,90,1

In [ ]:
merged.shape

(2919, 87)

## Varnames
### CNTLAFFI is the indicator for public/private.
1 - public

3/4 - private

all are non-profit
### STUSRV8 is the indicator for daycare.
1 - yes

rest - no

In [ ]:
merged = merged[['UNITID', 'INSTNM', 'EIN', 'OPEID',
                 'IALIAS', 'ADDR', 'CITY', 'STABBR',
                 'ZIP', 'WEBADDR', 'CSTOTLT', 'EFTOTAL',
                 'CNTLAFFI', 'STUSRV8']]
merged.head(10)

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,CSTOTLT,EFTOTAL,CNTLAFFI,STUSRV8
0,100654,Alabama A & M University,636001109,100200,AAMU,4900 Meridian Street,Normal,AL,35762,www.aamu.edu/,729,6614,1,1
1,100663,University of Alabama at Birmingham,636005396,105200,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,https://www.uab.edu/,6356,21160,1,0
2,100690,Amridge University,237034324,2503400,Southern Christian University Regions University,1200 Taylor Rd,Montgomery,AL,36117-3553,https://www.amridgeuniversity.edu/,171,636,4,0
3,100706,University of Alabama in Huntsville,630520830,105500,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,www.uah.edu/,2288,8743,1,1
4,100724,Alabama State University,636001101,100500,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,www.alasu.edu/,598,3870,1,0
5,100751,The University of Alabama,636001138,105100,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,www.ua.edu/,8929,39622,1,1
6,100760,Central Alabama Community College,631022757,100700,NaN,1675 Cherokee Rd,Alexander City,AL,35010,www.cacc.edu/,232,1910,1,0
7,100812,Athens State University,630701340,100800,NaN,300 N Beaty St,Athens,AL,35611,https://www.athens.edu/,837,2955,1,0
8,100830,Auburn University at Montgomery,636000724,831000,AUM||Auburn University at Montgomery|Auburn Mo...,7440 East Drive,Montgomery,AL,36117-3596,www.aum.edu/,1256,5189,1,1
9,100858,Auburn University,636000724,100900,NaN,NaN,Auburn,AL,36849,www.auburn.edu/,7764,33015,1,0

In [ ]:
merged.shape

(2919, 14)

In [ ]:
merged.to_csv('merged_basic.csv', index=False)

## MERGE WITH OTHER TABLES

In [ ]:
sal = pd.read_csv("SAL2023_IS_sorted.csv")
oc = pd.read_csv("S2023_OC_final_decimal.csv")

In [ ]:
# Merge with SAL first
merge_with_sal = pd.merge(merged, sal, on='UNITID', how='inner')
merge_with_sal.head(10)

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,CNTLAFFI,STUSRV8,SAINSTM,SAINSTW,SAOUTLM,SAOUTLW,AVGSALM,AVGSALW,AVGALLM,AVGALLW
0,100654,Alabama A & M University,636001109,100200,AAMU,4900 Meridian Street,Normal,AL,35762,www.aamu.edu/,...,1,1,139,127,10412890,8675484,74912.88,68310.90,110286.9382,94108.42955
1,100663,University of Alabama at Birmingham,636005396,105200,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,https://www.uab.edu/,...,1,0,423,530,57379658,65638438,135649.31,123846.11,110286.9382,94108.42955
2,100690,Amridge University,237034324,2503400,Southern Christian University Regions University,1200 Taylor Rd,Montgomery,AL,36117-3553,https://www.amridgeuniversity.edu/,...,4,0,25,6,1298408,550937,51936.32,91822.83,110286.9382,94108.42955
3,100706,University of Alabama in Huntsville,630520830,105500,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,www.uah.edu/,...,1,1,195,164,21688839,13418489,111224.82,81820.05,110286.9382,94108.42955
4,100724,Alabama State University,636001101,100500,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,www.alasu.edu/,...,1,0,101,104,8443989,7987039,83603.85,76798.45,110286.9382,94108.42955
5,100751,The University of Alabama,636001138,105100,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,www.ua.edu/,...,1,1,857,790,98595430,72380933,115047.18,91621.43,110286.9382,94108.42955
6,100760,Central Alabama Community College,631022757,100700,NaN,1675 Cherokee Rd,Alexander City,AL,35010,www.cacc.edu/,...,1,0,23,26,1469853,1659218,63906.65,63816.08,110286.9382,94108.42955
7,100812,Athens State University,630701340,100800,NaN,300 N Beaty St,Athens,AL,35611,https://www.athens.edu/,...,1,0,39,49,3517660,4421918,90196.41,90243.22,110286.9382,94108.42955
8,100830,Auburn University at Montgomery,636000724,831000,AUM||Auburn University at Montgomery|Auburn Mo...,7440 East Drive,Montgomery,AL,36117-3596,www.aum.edu/,...,1,1,113,116,10681950,9248980,94530.53,79732.59,110286.9382,94108.42955
9,100858,Auburn University,636000724,100900,NaN,NaN,Auburn,AL,36849,www.auburn.edu/,...,1,0,850,616,105331451,64811313,123919.35,105213.17,110286.9382,94108.42955

In [ ]:
merge_with_sal.shape

(2803, 22)

In [ ]:
# Merge with OC
merge_with_oc = pd.merge(merge_with_sal, oc, on='UNITID', how='inner')
merge_with_oc.head(10)

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,AVGSALW,AVGALLM,AVGALLW,OCCUPCAT,HRTOTLT,HRTOTLM,HRTOTLW,BLKPERC,HISPPERC,ASIAPERC
0,100654,Alabama A & M University,636001109,100200,AAMU,4900 Meridian Street,Normal,AL,35762,www.aamu.edu/,...,68310.90,110286.9382,94108.42955,100,566,204,362,0.874558,0.000000,0.019435
1,100663,University of Alabama at Birmingham,636005396,105200,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,https://www.uab.edu/,...,123846.11,110286.9382,94108.42955,100,7432,2371,5061,0.311760,0.022067,0.061356
2,100690,Amridge University,237034324,2503400,Southern Christian University Regions University,1200 Taylor Rd,Montgomery,AL,36117-3553,https://www.amridgeuniversity.edu/,...,91822.83,110286.9382,94108.42955,100,31,14,17,0.096774,0.000000,0.000000
3,100706,University of Alabama in Huntsville,630520830,105500,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,www.uah.edu/,...,81820.05,110286.9382,94108.42955,100,1055,490,565,0.120379,0.022749,0.035071
4,100724,Alabama State University,636001101,100500,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,www.alasu.edu/,...,76798.45,110286.9382,94108.42955,100,571,239,332,0.872154,0.003503,0.017513
5,100751,The University of Alabama,636001138,105100,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,www.ua.edu/,...,91621.43,110286.9382,94108.42955,100,4988,1874,3114,0.213512,0.021852,0.019447
6,100760,Central Alabama Community College,631022757,100700,NaN,1675 Cherokee Rd,Alexander City,AL,35010,www.cacc.edu/,...,63816.08,110286.9382,94108.42955,100,116,37,79,0.267241,0.008621,0.000000
7,100812,Athens State University,630701340,100800,NaN,300 N Beaty St,Athens,AL,35611,https://www.athens.edu/,...,90243.22,110286.9382,94108.42955,100,194,67,127,0.113402,0.015464,0.015464
8,100830,Auburn University at Montgomery,636000724,831000,AUM||Auburn University at Montgomery|Auburn Mo...,7440 East Drive,Montgomery,AL,36117-3596,www.aum.edu/,...,79732.59,110286.9382,94108.42955,100,464,169,295,0.312500,0.006466,0.040948
9,100858,Auburn University,636000724,100900,NaN,NaN,Auburn,AL,36849,www.auburn.edu/,...,105213.17,110286.9382,94108.42955,100,4899,1846,3053,0.137171,0.029190,0.022249

In [ ]:
merge_with_oc.shape

(2801, 29)

In [ ]:
merge_with_oc.to_csv('merged_intermediate.csv', index=False)

## Continue with S2023_IS_final

In [ ]:
df = pd.read_csv("S2023_IS_final_decimal.csv")
df.head(10)

,UNITID,SISCAT,HRTOTLT,HRTOTLM,HRTOTLW,PRFPERCW,BKAAPERCW,HISPERCW,AISAPERCW
0,100654,101,40,31,9,0.225000,0.125000,0.000000,0.025000
1,100654,102,53,31,22,0.415094,0.245283,0.000000,0.113208
2,100654,200,73,53,20,0.273973,0.178082,0.000000,0.068493
3,100663,200,904,576,328,0.362832,0.027655,0.005531,0.055310
4,100663,101,787,512,275,0.349428,0.021601,0.006353,0.054638
5,100663,102,732,406,326,0.445355,0.047814,0.015027,0.077869
6,100690,101,14,12,2,0.142857,0.000000,0.000000,0.000000
7,100690,102,7,5,2,0.285714,0.142857,0.000000,0.000000
8,100706,101,75,61,14,0.186667,0.013333,0.000000,0.040000
9,100706,102,87,56,31,0.356322,0.022989,0.011494,0.080460

In [ ]:
df = df.drop(columns=['HRTOTLT', 'HRTOTLM', 'HRTOTLW'])
df.head()

   UNITID  SISCAT  PRFPERCW  BKAAPERCW  HISPERCW  AISAPERCW
0  100654     101  0.225000   0.125000  0.000000   0.025000
1  100654     102  0.415094   0.245283  0.000000   0.113208
2  100654     200  0.273973   0.178082  0.000000   0.068493
3  100663     200  0.362832   0.027655  0.005531   0.055310
4  100663     101  0.349428   0.021601  0.006353   0.054638

In [ ]:
# Step 2: Reshape the data with pivot
# 'UNITID' becomes the index, 'SISCAT' values become column suffixes
pivoted_df = df.pivot(index="UNITID", columns="SISCAT", values=[col for col in df.columns if col not in ["UNITID", "SISCAT"]])

In [ ]:
# Step 3: Rename the columns
# Flatten the multi-level column index created by pivot
pivoted_df.columns = [f"{col[0]}_{int(col[1])}" for col in pivoted_df.columns]

In [ ]:
pivoted_df.reset_index(inplace=True)

In [ ]:
pivoted_df.fillna(0, inplace=True)

In [ ]:
pivoted_df.head(10)

,UNITID,PRFPERCW_101,PRFPERCW_102,PRFPERCW_200,BKAAPERCW_101,BKAAPERCW_102,BKAAPERCW_200,HISPERCW_101,HISPERCW_102,HISPERCW_200,AISAPERCW_101,AISAPERCW_102,AISAPERCW_200
0,100654,0.225000,0.415094,0.273973,0.125000,0.245283,0.178082,0.000000,0.000000,0.000000,0.025000,0.113208,0.068493
1,100663,0.349428,0.445355,0.362832,0.021601,0.047814,0.027655,0.006353,0.015027,0.005531,0.054638,0.077869,0.055310
2,100690,0.142857,0.285714,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,100706,0.186667,0.356322,0.261438,0.013333,0.022989,0.019608,0.000000,0.011494,0.006536,0.040000,0.080460,0.058824
4,100724,0.474576,0.452830,0.471698,0.338983,0.320755,0.339623,0.000000,0.000000,0.000000,0.033898,0.056604,0.047170
5,100751,0.316418,0.420091,0.352410,0.023881,0.031963,0.025602,0.011940,0.011416,0.012048,0.020896,0.047945,0.039157
6,100760,0.000000,0.000000,0.518519,0.000000,0.000000,0.074074,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,100812,0.560000,0.636364,0.618182,0.160000,0.000000,0.072727,0.000000,0.060606,0.036364,0.000000,0.090909,0.036364
8,100830,0.339286,0.424242,0.376068,0.053571,0.045455,0.051282,0.000000,0.000000,0.000000,0.000000,0.045455,0.025641
9,100858,0.314070,0.419204,0.340081,0.015075,0.023419,0.016194,0.012563,0.018735,0.016194,0.040201,0.046838,0.044534

In [ ]:
pivoted_df.to_csv('S2023_IS_FINAL.csv', index=False)

In [ ]:
df = pd.read_csv("S2023_IS_flattened_decimal.csv")
df.head(10)

,UNITID,PRFPERCW_101,PRFPERCW_102,PRFPERCW_200,BKAAPERCW_101,BKAAPERCW_102,BKAAPERCW_200,HISPERCW_101,HISPERCW_102,HISPERCW_200,AISAPERCW_101,AISAPERCW_102,AISAPERCW_200
0,100654,0.225000,0.415094,0.273973,0.125000,0.245283,0.178082,0.000000,0.000000,0.000000,0.025000,0.113208,0.068493
1,100663,0.349428,0.445355,0.362832,0.021601,0.047814,0.027655,0.006353,0.015027,0.005531,0.054638,0.077869,0.055310
2,100690,0.142857,0.285714,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,100706,0.186667,0.356322,0.261438,0.013333,0.022989,0.019608,0.000000,0.011494,0.006536,0.040000,0.080460,0.058824
4,100724,0.474576,0.452830,0.471698,0.338983,0.320755,0.339623,0.000000,0.000000,0.000000,0.033898,0.056604,0.047170
5,100751,0.316418,0.420091,0.352410,0.023881,0.031963,0.025602,0.011940,0.011416,0.012048,0.020896,0.047945,0.039157
6,100760,0.000000,0.000000,0.518519,0.000000,0.000000,0.074074,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,100812,0.560000,0.636364,0.618182,0.160000,0.000000,0.072727,0.000000,0.060606,0.036364,0.000000,0.090909,0.036364
8,100830,0.339286,0.424242,0.376068,0.053571,0.045455,0.051282,0.000000,0.000000,0.000000,0.000000,0.045455,0.025641
9,100858,0.314070,0.419204,0.340081,0.015075,0.023419,0.016194,0.012563,0.018735,0.016194,0.040201,0.046838,0.044534

In [ ]:
# Merge with IS
merge_with_is = pd.merge(merge_with_oc, df, on='UNITID', how='inner')
merge_with_is.head(10)

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,PRFPERCW_200,BKAAPERCW_101,BKAAPERCW_102,BKAAPERCW_200,HISPERCW_101,HISPERCW_102,HISPERCW_200,AISAPERCW_101,AISAPERCW_102,AISAPERCW_200
0,100654,Alabama A & M University,636001109,100200,AAMU,4900 Meridian Street,Normal,AL,35762,www.aamu.edu/,...,0.273973,0.125000,0.245283,0.178082,0.000000,0.000000,0.000000,0.025000,0.113208,0.068493
1,100663,University of Alabama at Birmingham,636005396,105200,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,https://www.uab.edu/,...,0.362832,0.021601,0.047814,0.027655,0.006353,0.015027,0.005531,0.054638,0.077869,0.055310
2,100690,Amridge University,237034324,2503400,Southern Christian University Regions University,1200 Taylor Rd,Montgomery,AL,36117-3553,https://www.amridgeuniversity.edu/,...,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,100706,University of Alabama in Huntsville,630520830,105500,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,www.uah.edu/,...,0.261438,0.013333,0.022989,0.019608,0.000000,0.011494,0.006536,0.040000,0.080460,0.058824
4,100724,Alabama State University,636001101,100500,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,www.alasu.edu/,...,0.471698,0.338983,0.320755,0.339623,0.000000,0.000000,0.000000,0.033898,0.056604,0.047170
5,100751,The University of Alabama,636001138,105100,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,www.ua.edu/,...,0.352410,0.023881,0.031963,0.025602,0.011940,0.011416,0.012048,0.020896,0.047945,0.039157
6,100760,Central Alabama Community College,631022757,100700,NaN,1675 Cherokee Rd,Alexander City,AL,35010,www.cacc.edu/,...,0.518519,0.000000,0.000000,0.074074,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,100812,Athens State University,630701340,100800,NaN,300 N Beaty St,Athens,AL,35611,https://www.athens.edu/,...,0.618182,0.160000,0.000000,0.072727,0.000000,0.060606,0.036364,0.000000,0.090909,0.036364
8,100830,Auburn University at Montgomery,636000724,831000,AUM||Auburn University at Montgomery|Auburn Mo...,7440 East Drive,Montgomery,AL,36117-3596,www.aum.edu/,...,0.376068,0.053571,0.045455,0.051282,0.000000,0.000000,0.000000,0.000000,0.045455,0.025641
9,100858,Auburn University,636000724,100900,NaN,NaN,Auburn,AL,36849,www.auburn.edu/,...,0.340081,0.015075,0.023419,0.016194,0.012563,0.018735,0.016194,0.040201,0.046838,0.044534

In [ ]:
merge_with_is.shape

(2431, 41)

In [ ]:
merge_with_is.to_csv('merged_final.csv', index=False)

## Finalized Table for IPEDS 2023-24