#HATE/VAWA DATA LOADING

In [ ]:
import pandas as pd

df1 = pd.read_csv("Oncampushate202122.csv")
df1.head()

<ipython-input-1-cfeb25aea5dc>:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("Oncampushate202122.csv")

,UNITID_P,INSTNM,OPEID,BRANCH,Address,City,State,ZIP,sector_cd,Sector_desc,...,VANDAL_REL22,VANDAL_SEX22,VANDAL_GEN22,VANDAL_GID22,VANDAL_DIS22,VANDAL_ET22,VANDAL_NAT22,FILTER20,FILTER21,FILTER22
0,100654001,Alabama A & M University,100200,Main Campus,4900 MERIDIAN ST,NORMAL,AL,35762,1,"Public, 4-year or above",...,0,0,0,0,0,0,0,1,1,1
1,100663001,University of Alabama at Birmingham,105200,Main Campus,"ADMINISTRATION BLDG SUITE 1070, 701 20th Stree...",BIRMINGHAM,AL,352940110,1,"Public, 4-year or above",...,0,0,0,0,0,0,0,1,1,1
2,100663002,University of Alabama at Birmingham,105200,Huntsville Regional Medical Campus,301 Governors Drive SW,Huntsville,AL,35801,1,"Public, 4-year or above",...,0,0,0,0,0,0,0,1,1,1
3,100706001,University of Alabama in Huntsville,105500,Main Campus,301 SPARKMAN DR,HUNTSVILLE,AL,35899,1,"Public, 4-year or above",...,0,0,0,0,0,0,0,1,1,1
4,100724001,Alabama State University,100500,Main Campus,915 SOUTH JACKSON ST,MONTGOMERY,AL,361040271,1,"Public, 4-year or above",...,0,0,0,0,0,0,0,1,1,1

In [ ]:
df2 = pd.read_csv("Oncampusvawa202122.csv")
df2.head()

,UNITID_P,INSTNM,OPEID,BRANCH,Address,City,State,ZIP,sector_cd,Sector_desc,...,STALK20,DOMEST21,DATING21,STALK21,DOMEST22,DATING22,STALK22,FILTER20,FILTER21,FILTER22
0,100654001,Alabama A & M University,100200,Main Campus,4900 MERIDIAN ST,NORMAL,AL,35762,1,"Public, 4-year or above",...,0.0,2.0,3.0,1.0,16,8,1,1,1,1
1,100663001,University of Alabama at Birmingham,105200,Main Campus,"ADMINISTRATION BLDG SUITE 1070, 701 20th Stree...",BIRMINGHAM,AL,352940110,1,"Public, 4-year or above",...,10.0,12.0,13.0,12.0,15,45,22,1,1,1
2,100663002,University of Alabama at Birmingham,105200,Huntsville Regional Medical Campus,301 Governors Drive SW,Huntsville,AL,35801,1,"Public, 4-year or above",...,0.0,0.0,0.0,0.0,2,0,0,1,1,1
3,100706001,University of Alabama in Huntsville,105500,Main Campus,301 SPARKMAN DR,HUNTSVILLE,AL,35899,1,"Public, 4-year or above",...,2.0,0.0,0.0,1.0,0,3,15,1,1,1
4,100724001,Alabama State University,100500,Main Campus,915 SOUTH JACKSON ST,MONTGOMERY,AL,361040271,1,"Public, 4-year or above",...,0.0,7.0,0.0,0.0,4,1,0,1,1,1

#Dropping irrelevant columns

In [ ]:
df1.drop(columns=['BRANCH', 'Address', 'ZIP', 'sector_cd', 'UNITID_P', 'FILTER20', 'FILTER21', 'FILTER22'], inplace=True)
df2.drop(columns=['BRANCH', 'Address', 'ZIP', 'sector_cd', 'UNITID_P', 'FILTER20', 'FILTER21', 'FILTER22'], inplace=True)
print(df1.shape)
print(df2.shape)
df1.head()

(10499, 386)
(10499, 17)

,INSTNM,OPEID,City,State,Sector_desc,men_total,women_total,Total,MURD20,MURD_RAC20,...,INTIM_NAT22,VANDAL22,VANDAL_RAC22,VANDAL_REL22,VANDAL_SEX22,VANDAL_GEN22,VANDAL_GID22,VANDAL_DIS22,VANDAL_ET22,VANDAL_NAT22
0,Alabama A & M University,100200,NORMAL,AL,"Public, 4-year or above",2369.0,3638.0,6007.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,University of Alabama at Birmingham,105200,BIRMINGHAM,AL,"Public, 4-year or above",7903.0,13736.0,21639.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,University of Alabama at Birmingham,105200,Huntsville,AL,"Public, 4-year or above",7903.0,13736.0,21639.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,University of Alabama in Huntsville,105500,HUNTSVILLE,AL,"Public, 4-year or above",5333.0,3904.0,9237.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,Alabama State University,100500,MONTGOMERY,AL,"Public, 4-year or above",1347.0,2481.0,3828.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

#Merging schools that have multiple entries into one

In [ ]:
# List of columns to apply 'first'
first_columns = ['OPEID', 'City', 'State', 'Sector_desc', 'men_total', 'women_total', 'Total']
numeric_cols1 = df1.select_dtypes(include=['number']).columns.tolist()
numeric_cols2 = df2.select_dtypes(include=['number']).columns.tolist()

# Generate the aggregation dictionary
agg_dict1 = {col: 'first' for col in first_columns}  # Apply 'first' for specific columns
agg_dict1.update({col: 'sum' for col in numeric_cols1 if col not in first_columns})  # Apply 'sum' for others

agg_dict2 = {col: 'first' for col in first_columns}  # Apply 'first' for specific columns
agg_dict2.update({col: 'sum' for col in numeric_cols2 if col not in first_columns})  # Apply 'sum' for others

hate = df1.groupby('INSTNM', as_index=False).agg(agg_dict1)
vawa = df2.groupby('INSTNM', as_index=False).agg(agg_dict2)
print(hate.shape)
print(vawa.shape)

(5684, 386)
(5684, 17)

In [ ]:
hate.head(10)

,INSTNM,OPEID,City,State,Sector_desc,men_total,women_total,Total,MURD20,MURD_RAC20,...,INTIM_NAT22,VANDAL22,VANDAL_RAC22,VANDAL_REL22,VANDAL_SEX22,VANDAL_GEN22,VANDAL_GID22,VANDAL_DIS22,VANDAL_ET22,VANDAL_NAT22
0,A Better U Beauty Barber Academy,4283300,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,A T Still University of Health Sciences,247700,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,ABC Adult School,4227000,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,ABC Beauty Academy,4168800,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,ABCO Technology,4242600,Los Angeles,CA,"Private for-profit, less-than 2-year",107.0,10.0,117.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,AMG School of Nursing,4234900,Brooklyn,NY,"Private for-profit, less-than 2-year",79.0,400.0,479.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
6,AOMA Graduate School of Integrative Medicine,3156400,AUSTIN,TX,"Private for-profit, 4-year or above",24.0,111.0,135.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
7,ASI Career Institute,4188700,Turnersville,NJ,"Private for-profit, less-than 2-year",4.0,45.0,49.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
8,ASPIRA City College,3109100,Philadelphia,PA,"Private nonprofit, 2-year",3.0,8.0,11.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
9,ATA Career Education,4038302,Spring Hill,FL,"Private for-profit, 2-year",12.0,182.0,194.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
vawa.head()

,INSTNM,OPEID,City,State,Sector_desc,men_total,women_total,Total,DOMEST20,DATING20,STALK20,DOMEST21,DATING21,STALK21,DOMEST22,DATING22,STALK22
0,A Better U Beauty Barber Academy,4283300,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,A T Still University of Health Sciences,247700,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,0.0,0.0,1.0,7.0,0.0,0.0,0,0,0
2,ABC Adult School,4227000,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,ABC Beauty Academy,4168800,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
4,ABCO Technology,4242600,Los Angeles,CA,"Private for-profit, less-than 2-year",107.0,10.0,117.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

# Combining crimes over the three years into one column, and compute their average

In [ ]:
hate['AVG_crimes'] = hate.iloc[:, 8:385].sum(axis=1)
vawa['AVG_crimes'] = vawa.iloc[:, 8:16].sum(axis=1)
vawa.head()

,INSTNM,OPEID,City,State,Sector_desc,men_total,women_total,Total,DOMEST20,DATING20,STALK20,DOMEST21,DATING21,STALK21,DOMEST22,DATING22,STALK22,AVG_crimes
0,A Better U Beauty Barber Academy,4283300,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0
1,A T Still University of Health Sciences,247700,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,0.0,0.0,1.0,7.0,0.0,0.0,0,0,0,8.0
2,ABC Adult School,4227000,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0
3,ABC Beauty Academy,4168800,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0
4,ABCO Technology,4242600,Los Angeles,CA,"Private for-profit, less-than 2-year",107.0,10.0,117.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0

In [ ]:
vawa = vawa.drop(vawa.columns[8:17], axis=1)
hate = hate.drop(hate.columns[8:386], axis=1)
hate.head()

,INSTNM,OPEID,City,State,Sector_desc,men_total,women_total,Total,AVG_crimes
0,A Better U Beauty Barber Academy,4283300,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.0
1,A T Still University of Health Sciences,247700,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,0.0
2,ABC Adult School,4227000,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.0
3,ABC Beauty Academy,4168800,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.0
4,ABCO Technology,4242600,Los Angeles,CA,"Private for-profit, less-than 2-year",107.0,10.0,117.0,0.0

In [ ]:
hate['AVG_crimes'] = hate['AVG_crimes'] / 3
vawa['AVG_crimes'] = vawa['AVG_crimes'] / 3
vawa.head()

,INSTNM,OPEID,City,State,Sector_desc,men_total,women_total,Total,AVG_crimes
0,A Better U Beauty Barber Academy,4283300,Albuquerque,NM,"Private for-profit, less-than 2-year",27.0,11.0,38.0,0.000000
1,A T Still University of Health Sciences,247700,Kirksville,MO,"Private nonprofit, 4-year or above",1353.0,2370.0,3723.0,2.666667
2,ABC Adult School,4227000,Cerritos,CA,"Public, less-than 2-year",41.0,152.0,193.0,0.000000
3,ABC Beauty Academy,4168800,Richardson,TX,"Private for-profit, less-than 2-year",6.0,58.0,64.0,0.000000
4,ABCO Technology,4242600,Los Angeles,CA,"Private for-profit, less-than 2-year",107.0,10.0,117.0,0.000000

In [ ]:
hate.to_csv('hate_cleaned_202122.csv', index=False)
vawa.to_csv('vawa_cleaned_202122.csv', index=False)