In [1]:
import pandas as pd

ipeds_css = pd.read_csv("merged_ipeds_css_decimal.csv")
irs = pd.read_csv("irs990.csv")
ipeds_css.head()

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,HISPERCW_200,AISAPERCW_101,AISAPERCW_102,AISAPERCW_200,AVGPERY_HATE,PERTHOU_HATE,AVGALL_HATE,AVGPERY_VAWA,PERTHOU_VAWA,AVGALL_VAWA
0,100654,Alabama A & M University,636001109,100200,AAMU,4900 Meridian Street,Normal,AL,35762,www.aamu.edu/,...,0.000000,0.025000,0.113208,0.068493,0.000000,0,0.075803,11.666667,1.942178569,0.473938
1,100663,University of Alabama at Birmingham,636005396,105200,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,https://www.uab.edu/,...,0.005531,0.054638,0.077869,0.055310,1.333333,0.061617142,0.075803,48.333333,2.233621393,0.473938
2,100706,University of Alabama in Huntsville,630520830,105500,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,www.uah.edu/,...,0.006536,0.040000,0.080460,0.058824,0.666667,0.072173505,0.075803,2.333333,0.252607268,0.473938
3,100724,Alabama State University,636001101,100500,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,www.alasu.edu/,...,0.000000,0.033898,0.056604,0.047170,0.000000,0,0.075803,5.333333,1.393242773,0.473938
4,100751,The University of Alabama,636001138,105100,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,www.ua.edu/,...,0.012048,0.020896,0.047945,0.039157,1.333333,0.034502985,0.075803,24.666667,0.638305213,0.473938

In [2]:
merged_df = pd.merge(ipeds_css, irs, on='EIN', how='left')
merged_df.head(10)

,UNITID,INSTNM_x,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,INSTNM_y,IRS_MONTH,YEAR,PERCENTAGE_WOMEN_TRUSTEES,PERCENTAGE_WOMEN_KEY_EMPLOYEES,WHISTLEBLOWER_POLICY,CEO_REVIEWED_COMPENSATION,OTHER_REVIEWED_COMPENSATION,MALE_TO_FEMALE_PAY_RATIO,PRESIDENT_TO_AVERAGE_PAY_RATIO
0,100654,Alabama A & M University,636001109,100200,AAMU,4900 Meridian Street,Normal,AL,35762,www.aamu.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100663,University of Alabama at Birmingham,636005396,105200,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,https://www.uab.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100706,University of Alabama in Huntsville,630520830,105500,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,www.uah.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100724,Alabama State University,636001101,100500,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,www.alasu.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100751,The University of Alabama,636001138,105100,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,www.ua.edu/,...,THE BOARD OF TRUSTEES OF THE UNIVERSITY OF ALA...,08A,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,100760,Central Alabama Community College,631022757,100700,NaN,1675 Cherokee Rd,Alexander City,AL,35010,www.cacc.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,100812,Athens State University,630701340,100800,NaN,300 N Beaty St,Athens,AL,35611,https://www.athens.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,100830,Auburn University at Montgomery,636000724,831000,AUM||Auburn University at Montgomery|Auburn Mo...,7440 East Drive,Montgomery,AL,36117-3596,www.aum.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,100858,Auburn University,636000724,100900,NaN,NaN,Auburn,AL,36849,www.auburn.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,100937,Birmingham-Southern College,630708730,101200,BSC,900 Arkadelphia Road,Birmingham,AL,35254,www.bsc.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
merged_df.shape

(2719, 57)

In [4]:
merged_df.rename(columns={'INSTNM_x': 'INSTNM'}, inplace=True)
merged_df = merged_df.drop("INSTNM_y", axis=1)
merged_df.head()

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,AVGALL_VAWA,IRS_MONTH,YEAR,PERCENTAGE_WOMEN_TRUSTEES,PERCENTAGE_WOMEN_KEY_EMPLOYEES,WHISTLEBLOWER_POLICY,CEO_REVIEWED_COMPENSATION,OTHER_REVIEWED_COMPENSATION,MALE_TO_FEMALE_PAY_RATIO,PRESIDENT_TO_AVERAGE_PAY_RATIO
0,100654,Alabama A & M University,636001109,100200,AAMU,4900 Meridian Street,Normal,AL,35762,www.aamu.edu/,...,0.473938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100663,University of Alabama at Birmingham,636005396,105200,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,https://www.uab.edu/,...,0.473938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100706,University of Alabama in Huntsville,630520830,105500,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,www.uah.edu/,...,0.473938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100724,Alabama State University,636001101,100500,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,www.alasu.edu/,...,0.473938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100751,The University of Alabama,636001138,105100,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,www.ua.edu/,...,0.473938,08A,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
merged_df.shape

(2719, 56)

Renaming Columns metadata

In [6]:
merged_df.rename(columns={'CSTOTLT': 'DEGREETOT'}, inplace=True)
merged_df.rename(columns={'EFTOTAL': 'ENROLLTOT'}, inplace=True)
merged_df.rename(columns={'SAINSTM': 'ACADEMICPOPM'}, inplace=True)
merged_df.rename(columns={'SAINSTW': 'ACADEMICPOPF'}, inplace=True)
merged_df.rename(columns={'SAOUTLM': 'SALARYTOTM'}, inplace=True)
merged_df.rename(columns={'SAOUTLW': 'SALARYTOTF'}, inplace=True)
merged_df.rename(columns={'AVGSALM': 'SALARYPPM'}, inplace=True) #
merged_df.rename(columns={'AVGSALW': 'SALARYPPF'}, inplace=True) #
merged_df.rename(columns={'OC_BLKPERC': 'NONACD_BLKPCT'}, inplace=True)
merged_df.rename(columns={'OC_HISPPERC': 'NONACD_HSPPCT'}, inplace=True)
merged_df.rename(columns={'OC_ASIAPERC': 'NONACD_ASIAPCT'}, inplace=True)
merged_df.rename(columns={'PRFPERCW_101': 'PROFWOMENPCT'}, inplace=True)
merged_df.rename(columns={'PRFPERCW_102': 'ASSOCPROFWOMENPCT'}, inplace=True)
merged_df.rename(columns={'PRFPERCW_200': 'TENUREWOMENPCT'}, inplace=True)
merged_df.rename(columns={'BKAAPERCW_101': 'BLACKPROFWOMENPCT'}, inplace=True)
merged_df.rename(columns={'BKAAPERCW_102': 'BLACKASSOCPROFWOMENPCT'}, inplace=True)
merged_df.rename(columns={'BKAAPERCW_200': 'BLACKTENUREWOMENPCT'}, inplace=True)
merged_df.rename(columns={'HISPERCW_101': 'HISPANICPROFWOMENPCT'}, inplace=True)
merged_df.rename(columns={'HISPERCW_102': 'HISPANICASSOCPROFWOMENPCT'}, inplace=True)
merged_df.rename(columns={'HISPERCW_200': 'HISPANICTENUREWOMENPCT'}, inplace=True)
merged_df.rename(columns={'AISAPERCW_101': 'ASIANPROFWOMENPCT'}, inplace=True)
merged_df.rename(columns={'AISAPERCW_102': 'ASIANASSOCPROFWOMENPCT'}, inplace=True)
merged_df.rename(columns={'AISAPERCW_200': 'ASIANTENUREWOMENPCT'}, inplace=True)
merged_df.rename(columns={'AVGPERY_HATE': 'YEARLYHATECRIME'}, inplace=True)
merged_df.rename(columns={'PERTHOU_HATE': 'YEARLYHATECRIME1K'}, inplace=True)
merged_df.rename(columns={'AVGPERY_VAWA': 'YEARLYVAWA'}, inplace=True)
merged_df.rename(columns={'PERTHOU_VAWA': 'YEARLYVAWA1K'}, inplace=True)
merged_df.rename(columns={'STUSRV8': 'HASDAYCARE'}, inplace=True)
merged_df.head()

,UNITID,INSTNM,EIN,OPEID,IALIAS,ADDR,CITY,STABBR,ZIP,WEBADDR,...,AVGALL_VAWA,IRS_MONTH,YEAR,PERCENTAGE_WOMEN_TRUSTEES,PERCENTAGE_WOMEN_KEY_EMPLOYEES,WHISTLEBLOWER_POLICY,CEO_REVIEWED_COMPENSATION,OTHER_REVIEWED_COMPENSATION,MALE_TO_FEMALE_PAY_RATIO,PRESIDENT_TO_AVERAGE_PAY_RATIO
0,100654,Alabama A & M University,636001109,100200,AAMU,4900 Meridian Street,Normal,AL,35762,www.aamu.edu/,...,0.473938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100663,University of Alabama at Birmingham,636005396,105200,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,https://www.uab.edu/,...,0.473938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100706,University of Alabama in Huntsville,630520830,105500,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,www.uah.edu/,...,0.473938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100724,Alabama State University,636001101,100500,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,www.alasu.edu/,...,0.473938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100751,The University of Alabama,636001138,105100,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,www.ua.edu/,...,0.473938,08A,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Removing variables

In [7]:
merged_df = merged_df.drop(["AVGALLM",
                            "AVGALLW",
                            "AVGALL_HATE",
                            "AVGALL_VAWA",
                            "OCCUPCAT",
                            "HRTOTLT",
                            "HRTOTLM",
                            "HRTOTLW",
                            "BLKPERC",
                            "HISPPERC",
                            "ASIAPERC",
                            ], axis=1)

In [8]:
merged_df.shape

(2719, 45)

In [9]:
merged_df.columns

Index(['UNITID', 'INSTNM', 'EIN', 'OPEID', 'IALIAS', 'ADDR', 'CITY', 'STABBR',
       'ZIP', 'WEBADDR', 'DEGREETOT', 'ENROLLTOT', 'CNTLAFFI', 'HASDAYCARE',
       'ACADEMICPOPM', 'ACADEMICPOPF', 'SALARYTOTM', 'SALARYTOTF', 'SALARYPPM',
       'SALARYPPF', 'PROFWOMENPCT', 'ASSOCPROFWOMENPCT', 'TENUREWOMENPCT',
       'BLACKPROFWOMENPCT', 'BLACKASSOCPROFWOMENPCT', 'BLACKTENUREWOMENPCT',
       'HISPANICPROFWOMENPCT', 'HISPANICASSOCPROFWOMENPCT',
       'HISPANICTENUREWOMENPCT', 'ASIANPROFWOMENPCT', 'ASIANASSOCPROFWOMENPCT',
       'ASIANTENUREWOMENPCT', 'YEARLYHATECRIME', 'YEARLYHATECRIME1K',
       'YEARLYVAWA', 'YEARLYVAWA1K', 'IRS_MONTH', 'YEAR',
       'PERCENTAGE_WOMEN_TRUSTEES', 'PERCENTAGE_WOMEN_KEY_EMPLOYEES',
       'WHISTLEBLOWER_POLICY', 'CEO_REVIEWED_COMPENSATION',
       'OTHER_REVIEWED_COMPENSATION', 'MALE_TO_FEMALE_PAY_RATIO',
       'PRESIDENT_TO_AVERAGE_PAY_RATIO'],
      dtype='object')

In [10]:
merged_df.to_csv("gf2025_final.csv", index=False)